import type { IDebugEventSink } from "@/application/ports/debug";
import type { SddFrameworkPort, SddOperationResult, SpecContext } from "@/application/ports/sdd";
import type { TaskPlan } from "@/domain/planning/types";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

/**
 * Mock SDD adapter used in --debug-flow mode.
 * Creates stub artifact files without invoking the real cc-sdd executable,
 * so the full workflow can run offline without any external tools installed.
 */
export class MockSddAdapter implements SddFrameworkPort {
  constructor(private readonly sink?: IDebugEventSink) {}

  async initSpec(ctx: SpecContext): Promise<SddOperationResult> {
    const artifactPath = join(ctx.specDir, "spec.json");
    try {
      await mkdir(dirname(artifactPath), { recursive: true });
      const specJson = {
        specName: ctx.specName,
        language: ctx.language,
        approvals: {
          human_interaction: { approved: false },
          requirements: { approved: false },
          design: { approved: false },
          tasks: { approved: false },
        },
        ready_for_implementation: false,
      };
      await writeFile(artifactPath, JSON.stringify(specJson, null, 2), { flag: "w" });
      // Create a seed requirements.md so HUMAN_INTERACTION has content to present
      const requirementsPath = join(ctx.specDir, "requirements.md");
      await writeFile(
        requirementsPath,
        `# Requirements\n\n<!-- Describe the feature requirements for spec: ${ctx.specName} -->\n`,
        { flag: "wx" }, // only create if not already present
      ).catch((err: NodeJS.ErrnoException) => {
        if (err.code !== "EEXIST") throw err;
      });
      this.emitOperation("initSpec", ctx.specName, { ok: true, artifactPath });
      return { ok: true, artifactPath };
    } catch (err) {
      return this.failResult("initSpec", ctx.specName, err);
    }
  }

  async validatePrerequisites(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("validatePrerequisites", ctx, "requirements.md", undefined);
  }

  async validateRequirements(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("validateRequirements", ctx, "requirements.md", undefined);
  }

  async reflectBeforeDesign(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("reflectBeforeDesign", ctx, "requirements.md", undefined);
  }

  async reflectBeforeTasks(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("reflectBeforeTasks", ctx, "design.md", undefined);
  }

  async validateGap(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("validateGap", ctx, "requirements.md", undefined);
  }

  async validateTasks(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("validateTasks", ctx, "tasks.md", undefined);
  }

  async generateRequirements(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub(
      "generateRequirements",
      ctx,
      "requirements.md",
      "# Requirements (mock)\n\nGenerated by --debug-flow mock.\n",
    );
  }

  async generateDesign(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("generateDesign", ctx, "design.md", "# Design (mock)\n\nGenerated by --debug-flow mock.\n");
  }

  async validateDesign(ctx: SpecContext): Promise<SddOperationResult> {
    return this.runStub("validateDesign", ctx, "design.md", undefined);
  }

  async generateTasks(ctx: SpecContext): Promise<SddOperationResult> {
    const result = await this.runStub(
      "generateTasks",
      ctx,
      "tasks.md",
      "# Tasks (mock)\n\nGenerated by --debug-flow mock.\n",
    );
    if (result.ok) {
      // Set ready_for_implementation so IMPLEMENTATION phase can proceed without manual intervention.
      await this.setReadyForImplementation(ctx);
      // Write a stub TaskPlan JSON so ImplementationLoopService can load and execute it.
      await this.writeStubTaskPlan(ctx);
    }
    return result;
  }

  /**
   * Writes a minimal stub TaskPlan JSON to `.memory/tasks/task_<specName>.json`
   * under process.cwd() (the workspace root used by createImplementationLoopService).
   * ImplementationLoopService.run() looks up the plan by specName as the planId.
   */
  private async writeStubTaskPlan(ctx: SpecContext): Promise<void> {
    const workspaceRoot = process.cwd();

    const now = new Date().toISOString();
    const plan: TaskPlan = {
      id: ctx.specName,
      goal: `Implement spec: ${ctx.specName}`,
      tasks: [
        {
          id: "task-1",
          title: "Implement the feature described in tasks.md",
          status: "pending",
          steps: [],
        },
      ],
      createdAt: now,
      updatedAt: now,
    };

    const planPath = join(workspaceRoot, ".memory", "tasks", `task_${ctx.specName}.json`);
    await mkdir(dirname(planPath), { recursive: true });
    await writeFile(planPath, JSON.stringify(plan, null, 2), "utf-8");
  }

  private async setReadyForImplementation(ctx: SpecContext): Promise<void> {
    const specJsonPath = join(ctx.specDir, "spec.json");
    let existing: Record<string, unknown> = {};
    try {
      existing = JSON.parse(await readFile(specJsonPath, "utf-8")) as Record<string, unknown>;
    } catch (err) {
      if (!(err instanceof Error && "code" in err && err.code === "ENOENT")) {
        console.warn(`[MockSddAdapter] Error reading/parsing ${specJsonPath}. Proceeding with an empty object.`, err);
      }
    }
    await writeFile(specJsonPath, JSON.stringify({ ...existing, ready_for_implementation: true }, null, 2), "utf-8");
  }

  private async runStub(
    operation: string,
    ctx: SpecContext,
    filename: string,
    content: string | undefined,
  ): Promise<SddOperationResult> {
    const artifactPath = join(ctx.specDir, filename);
    try {
      await mkdir(dirname(artifactPath), { recursive: true });
      // Only write if content provided (validate ops reuse existing artifacts)
      if (content !== undefined) {
        await writeFile(artifactPath, content, { flag: "w" });
      }
      const result: SddOperationResult = { ok: true, artifactPath };
      this.emitOperation(operation, ctx.specName, result);
      return result;
    } catch (err) {
      return this.failResult(operation, ctx.specName, err);
    }
  }

  private failResult(operation: string, specName: string, err: unknown): SddOperationResult {
    const result: SddOperationResult = {
      ok: false,
      error: { exitCode: 1, stderr: err instanceof Error ? err.message : String(err) },
    };
    this.emitOperation(operation, specName, result);
    return result;
  }

  private emitOperation(operation: string, specName: string, result: SddOperationResult): void {
    if (!this.sink) return;
    this.sink.emit({
      type: "sdd:operation",
      operation,
      specName,
      outcome: result.ok ? "ok" : "error",
      ...(result.ok ? { artifactPath: result.artifactPath } : {}),
      timestamp: new Date().toISOString(),
    });
  }
}
