import type { SddFrameworkPort, SddOperationResult, SpecContext } from "@/application/ports/sdd";
import type { TaskPlan } from "@/domain/planning/types";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

/**
 * Mock SDD adapter used in --debug-flow mode.
 * Creates stub artifact files without invoking the real cc-sdd executable,
 * so the full workflow can run offline without any external tools installed.
 */
export class MockSddAdapter implements SddFrameworkPort {
  generateRequirements(ctx: SpecContext): Promise<SddOperationResult> {
    return this.writeStub(ctx, "requirements.md", "# Requirements (mock)\n\nGenerated by --debug-flow mock.\n");
  }

  generateDesign(ctx: SpecContext): Promise<SddOperationResult> {
    return this.writeStub(ctx, "design.md", "# Design (mock)\n\nGenerated by --debug-flow mock.\n");
  }

  validateDesign(ctx: SpecContext): Promise<SddOperationResult> {
    return this.writeStub(ctx, "design.md", undefined);
  }

  async generateTasks(ctx: SpecContext): Promise<SddOperationResult> {
    const result = await this.writeStub(ctx, "tasks.md", "# Tasks (mock)\n\nGenerated by --debug-flow mock.\n");
    if (result.ok) {
      // Set ready_for_implementation so IMPLEMENTATION phase can proceed without manual intervention.
      await this.setReadyForImplementation(ctx);
      // Write a stub TaskPlan JSON so ImplementationLoopService can load and execute it.
      await this.writeStubTaskPlan(ctx);
    }
    return result;
  }

  /**
   * Writes a minimal stub TaskPlan JSON to `.memory/tasks/task_<specName>.json`
   * under process.cwd() (the workspace root used by createImplementationLoopService).
   * ImplementationLoopService.run() looks up the plan by specName as the planId.
   */
  private async writeStubTaskPlan(ctx: SpecContext): Promise<void> {
    const workspaceRoot = process.cwd();

    const now = new Date().toISOString();
    const plan: TaskPlan = {
      id: ctx.specName,
      goal: `Implement spec: ${ctx.specName}`,
      tasks: [
        {
          id: "task-1",
          title: "Implement the feature described in tasks.md",
          status: "pending",
          steps: [],
        },
      ],
      createdAt: now,
      updatedAt: now,
    };

    const planPath = join(workspaceRoot, ".memory", "tasks", `task_${ctx.specName}.json`);
    await mkdir(dirname(planPath), { recursive: true });
    await writeFile(planPath, JSON.stringify(plan, null, 2), "utf-8");
  }

  private async setReadyForImplementation(ctx: SpecContext): Promise<void> {
    const specJsonPath = join(ctx.specDir, "spec.json");
    let existing: Record<string, unknown> = {};
    try {
      existing = JSON.parse(await readFile(specJsonPath, "utf-8")) as Record<string, unknown>;
    } catch (err) {
      if (!(err instanceof Error && "code" in err && err.code === "ENOENT")) {
        console.warn(`[MockSddAdapter] Error reading/parsing ${specJsonPath}. Proceeding with an empty object.`, err);
      }
    }
    await writeFile(specJsonPath, JSON.stringify({ ...existing, ready_for_implementation: true }, null, 2), "utf-8");
  }

  private async writeStub(
    ctx: SpecContext,
    filename: string,
    content: string | undefined,
  ): Promise<SddOperationResult> {
    const artifactPath = join(ctx.specDir, filename);
    try {
      await mkdir(dirname(artifactPath), { recursive: true });
      // Only write if content provided (validateDesign reuses existing design.md)
      if (content !== undefined) {
        await writeFile(artifactPath, content, { flag: "w" });
      }
      return { ok: true, artifactPath };
    } catch (err) {
      return {
        ok: false,
        error: { exitCode: 1, stderr: err instanceof Error ? err.message : String(err) },
      };
    }
  }
}
